travis:
  secure:
    BINSTAR_TOKEN: D+MDlSylkXChVxrV8BrecvUYbFipw2ZNobqyBMYsbCNDEBCBrvanLBEfNJ6Czrc0ikejgZXM5gG0z1AtM7cy+m0GU6EYWiGQaZD0sRZJ6cyYThHo0zHLYGw6ZVno4OU4NW6TphTR/9yI7rJkMYB8anv3YX3Kh2Oe1L3TU62UBAK+KjSXHeJeH6Whjy7+qy3TkCqeP/r9XcSbnBTQ7doZpdLjMvWHBgbFVbX590V+9nXZh/sQtRB2Jau2UkjgryTR7z1EsTXm4cx5xOkW24YUKPOXUXW4y0GSdyR3MWYeiKtrpo+kXdhcYRJCP2GjdDGoaxMWcSrN/zxwG+HHVWUArhPxwbSRMInDh/nike1qWH+eguQH7rImwNqfp/JIMrlsHO9qhDTvQ4LKSxsq/zlPZqDj8GURtO0s5ZExf/hzlFvaRyEvohst1UG9yIYM2vtwulwccdkhKhNve0MSLpVICB2zk6DBfav5x5oQCoDNFMccYC+XcDMamflOpJFqawc+e3vLyGLbrIwE8FrRdOY5ZM4ZjxpTKAjRPTzrHvolaSMmLozDr+7rqZAqd5x2A4qAY9fRFX43PxANMegvMKRL7tnmfLgSPlXQzHQSoiSLWKSvT/zf2RBjDUJBYWnKUlnbB0Ql2THmtcK7esJpzPalCcnv/p8JCVafQld/wqL6I58=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
